{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-vault.fullname" . }}-ui
  labels:
    {{- include "simple-vault.ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      {{- include "simple-vault.ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "simple-vault.ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "simple-vault.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: ui
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ include "simple-vault.imageRegistry" . }}{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.ui.service.port }}
          protocol: TCP
        livenessProbe:
          {{- toYaml .Values.ui.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.ui.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.ui.resources | nindent 10 }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

